### ISSUE TITLE
JSCS: The disallowLeftStickedOperators rule is no longer supported

### ISSUE THREAD

**Issue by acostaf** [madskristensen/vswebessentials.com#47]
Getting 2.2 today I am getting this error now

23/06/2014 15:20:13: JSCS: containerController.js compilation failed: JSCS: The disallowLeftStickedOperators rule is no longer supported.
Please use the following rules instead:

requireSpaceBeforeBinaryOperators
requireSpaceBeforePostfixUnaryOperators
requireSpacesInConditionalExpression

**Comment by GProulx** [comment]
This issue was also reported (and corrected) on the WE2013 repository: madskristensen/WebEssentials2013#1228

Can be closed here.
