### ISSUE TITLE
Web Essentials 2015 doesn't Show up in VS "Extensions and Updates" menu

### ISSUE THREAD

**Issue by johnwhitlow69** [madskristensen/vswebessentials.com#74]
OK, so not a website issue exactly, but other versions of Web Essentials show up inside of the Visual Studio 2015 search and I'm sure plenty would like it.

**Comment by GProulx** [comment]
I just checked and Web Essentials 2015 now appears in the list. This can be closed.

![image](https://cloud.githubusercontent.com/assets/1680372/8735015/b3f5aad6-2bdb-11e5-921c-6b315e9c7699.png)
