### ISSUE TITLE
Links to new Visual Studio extensions for Bundling, minification and client-side compilation

### ISSUE THREAD

**Issue by GProulx** [madskristensen/vswebessentials.com#78]
Hi @madskristensen 

I could add a short text with a link to your [blog post](http://madskristensen.net/post/bundling-minification-and-client-side-compilation) and to the associate extension for each of those topics on the WE2015 documentation on the web site.

What do you think?

**Comment by madskristensen** [comment]
Awesome idea. Thanks!!
